# -*- coding: utf-8 -*-
"""analise_CEAPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kq06H5kv_JlIRl1mZnPJemO83D_9_U3J
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

"""### Leitura e tratamento"""

df = pd.read_csv(
    "despesa_ceaps_2022.csv",
    sep=";",
    encoding="latin-1",
    skiprows=1
)

print(df.columns)
df.head()

df["VALOR_REEMBOLSADO"] = (
    df["VALOR_REEMBOLSADO"]
    .astype(str)
    .str.replace(",", ".")
    .astype(float)
)

"""### Estatísticas macro do dataset"""

total_despesas = df.shape[0]
total_senadores = df["SENADOR"].nunique()
valor_total = df["VALOR_REEMBOLSADO"].sum()
media_por_senador = valor_total / total_senadores

print(f"Total de despesas: {total_despesas}")
print(f"Total de senadores: {total_senadores}")
print(f"Valor total reembolsado: R$ {valor_total:,.2f}")
print(f"Média por senador: R$ {media_por_senador:,.2f}")

"""### Ranking — quem gastou mais?"""

gastos_senador = (
    df.groupby("SENADOR", as_index=False)["VALOR_REEMBOLSADO"]
      .sum()
      .sort_values("VALOR_REEMBOLSADO", ascending=False)
)

gastos_senador.head(10)

"""#### Gráfico – Top 10 senadores"""

fig = px.bar(
    gastos_senador.head(10),
    x="VALOR_REEMBOLSADO",
    y="SENADOR",
    orientation="h",
    title="Top 10 Senadores com Maior Gasto em 2022",
    labels={
        "VALOR_REEMBOLSADO": "Valor Reembolsado (R$)",
        "SENADOR": ""
    }
)

fig.update_layout(yaxis=dict(autorange="reversed"))
fig.show()

"""### Distribuição dos gastos (outliers)"""

fig = px.box(
    gastos_senador,
    y="VALOR_REEMBOLSADO",
    title="Distribuição dos Gastos Totais por Senador"
)

fig.show()

"""### Gastos ao longo do ano (sazonalidade)"""

gastos_mes = (
    df.groupby("MES", as_index=False)["VALOR_REEMBOLSADO"]
      .sum()
)

fig = px.line(
    gastos_mes,
    x="MES",
    y="VALOR_REEMBOLSADO",
    markers=True,
    title="Evolução Mensal dos Gastos da CEAPS em 2022",
    labels={
        "MES": "Mês",
        "VALOR_REEMBOLSADO": "Valor Reembolsado (R$)"
    }
)

fig.show()

"""### Tipos de despesa — para onde vai o dinheiro?"""

gastos_tipo = (
    df.groupby("TIPO_DESPESA", as_index=False)["VALOR_REEMBOLSADO"]
      .sum()
      .sort_values("VALOR_REEMBOLSADO", ascending=False)
)

gastos_tipo.head(10)

fig = px.bar(
    gastos_tipo.head(8),
    x="VALOR_REEMBOLSADO",
    y="TIPO_DESPESA",
    orientation="h",
    title="Principais Tipos de Despesa da CEAPS (2022)",
    labels={
        "VALOR_REEMBOLSADO": "Valor Reembolsado (R$)",
        "TIPO_DESPESA": ""
    }
)

fig.update_layout(yaxis=dict(autorange="reversed"))
fig.show()

"""### Tipo de despesa por mês (eleições)"""

gastos_mes_tipo = (
    df.groupby(["MES", "TIPO_DESPESA"], as_index=False)["VALOR_REEMBOLSADO"]
      .sum()
)

fig = px.bar(
    gastos_mes_tipo,
    x="MES",
    y="VALOR_REEMBOLSADO",
    color="TIPO_DESPESA",
    title="Gastos Mensais por Tipo de Despesa – 2022",
)

fig.show()

"""### Senadores que mais concentraram gastos"""

top5 = gastos_senador.head(5)["SENADOR"]

df_top5 = df[df["SENADOR"].isin(top5)]

fig = px.line(
    df_top5.groupby(["MES", "SENADOR"], as_index=False)["VALOR_REEMBOLSADO"].sum(),
    x="MES",
    y="VALOR_REEMBOLSADO",
    color="SENADOR",
    markers=True,
    title="Evolução Mensal dos Gastos – Top 5 Senadores"
)

fig.show()



